.TH SNAKEGAME 1 "Oktober 2024" "Snake Game 1.0" "User Commands"
.SH NAME
snakegame \- A simple Snake game implemented in Python using Tkinter.

.SH SYNOPSIS
.B snakegame
[\fBoptions\fR]

.SH DESCRIPTION
The snakegame is a classic Snake game where the player controls the movement of the snake on the canvas and tries to eat obstacles while avoiding collisions with itself.

.SH OPTIONS
This game does not accept any command-line options.

.SH CONTROLS
The player can use the following keyboard arrows to control the snake:
.TP
\fBUp\fR
Move the snake up.
.TP
\fBDown\fR
Move the snake down.
.TP
\fBLeft\fR
Move the snake left.
.TP
\fBRight\fR
Move the snake right.

.SH AUTHOR
This Snake game was created by Elias De Hondt as an example project using Python and Tkinter.

.SH BUGS
No known bugs. Report bugs to <elias.dehondt@student.kdg.be>.