.TH pakket 1 "Oktober 2024" "Snake Game 1.0" "User Commands"
.SH NAME 
pakket \- program that shows a graphical uname \-a 
.SH SYNOPSIS 
.B pakket 
.RI [ options ] 
.br 
.SH DESCRIPTION 
This manual page explains the 
.B pakket 
program. This program uses zenity to show a warning message with uname \-a info
 .PP 
\fBpakket\fP is showing uname \-a info in X11 
.SH "SEE ALSO" 
  zenity(1), uname(1)
 AUTHOR
  Elias De Hondt <elias.dehondt@student.kdg.be>