############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 18/10/2024        #
############################
galaxy_info:
  author: Elias De Hondt
  description: Install Nginx or Remove Nginx
  company: EliasDH
  license: MIT
  min_ansible_version: "2.1"
  galaxy_tags: []
dependencies: []
