############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 18/10/2024        #
############################
- name: Setup Nginx
  hosts: node1
  become: true
  gather_facts: true
  tasks:
    - name: Include nginx task
      ansible.builtin.import_tasks:
        file: roles/nginx/tasks/tasks-main.yml