- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure Apache2 is not installed
  apt:
    name: apache2
    state: absent

- name: Copy custom HTML file
  template:
    src: /etc/ansible/roles/nginx/templates/index.html.j2
    dest: /var/www/html/index.html

- name: Check if website is running
  content: |
    #!/bin/bash
    if curl -s --head  http://localhost:80 | grep "200 OK" > /dev/null; then
      echo "Running"
    else
      echo "Not Running"
    fi
  register: website

- name: Show status
  debug:
    msg: "Website is running"
  when: website.rc == 0

- name: Show status
  debug:
    msg: "Website is not running"
  when: website.rc != 0